version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - frontend
      - backend

  server:
    build:
      context: ./server
      dockerfile: ../docker/server/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./server:/var/www/html
    environment:
      - APP_ENV=dev
    networks:
      - backend
      - db

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  db:
    driver: bridge

volumes:
  mongodb_data: