global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'server'
    static_configs:
      - targets: ['server:8000']
    metrics_path: '/metrics'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: '/metrics'

  - job_name: 'nginx'
    static_configs:
      - targets: ['client:80']
    metrics_path: '/metrics'