todo-platform
├── client
│   ├── src
│   │   ├── components
│   │   │   └── index.tsx
│   │   ├── pages
│   │   │   └── index.tsx
│   │   └── App.tsx
│   ├── package.json
│   └── README.md
├── server
│   ├── src
│   │   ├── Controller
│   │   │   └── TodoController.php
│   │   ├── Entity
│   │   │   └── Todo.php
│   │   └── Repository
│   │       └── TodoRepository.php
│   ├── .env
│   ├── composer.json
│   └── symfony.lock
├── docker
│   ├── client
│   │   └── Dockerfile
│   ├── server
│   │   └── Dockerfile
│   └── mongodb
│       └── Dockerfile
├── docker-compose.yml
└── README.md